apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: default
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090

