apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: devops-staging
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: catalog
  type: NodePort  
  ports:
    - port: 80
      targetPort: 8081