apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
  namespace: devops-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
      - name: docker-hub
      initContainers:
      - name: init-postgres
        image: busybox:stable
        command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/*"]
      containers:
      - name: postgres
        image: postgres:13.22
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret