apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: prod
  labels:
    app: otel
spec:
  selector:
    app: otel
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317

    - name: prometheus
      protocol: TCP
      port: 11337
      targetPort: 11337

  type: ClusterIP
