apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: default
  labels:
    app: catalog
spec:
  selector:
    app: catalog
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090

