apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: devops-staging
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP